### ISSUE TITLE
[Feature Request] Allow for single quotes ' as well as double quotes

### ISSUE THREAD

**Issue by NebularNerd** [joebeachjoebeach/json-path-finder#15]
Love the path finder, it makes handling some trickier paths a breeze 😁

One minor thing if you can add support is some json data I receive is enclosed in single quotes, this causes an error as we show below:
![image](https://github.com/joebeachjoebeach/json-path-finder/assets/8470449/34db3766-e188-488e-b62e-fe64b2176f4b)

Is it possible to add support for `'` single quotes to save having to change them all manually before pasting into the site?

Thanks, Andy. 😁

**Comment by joebeachjoebeach** [comment]
hi there! unfortunately, the [JSON spec](https://www.json.org/json-en.html) stipulates that all strings must be in double quotes, and the data you're pasting doesn't adhere to that standard
> A value can be a string in double quotes, or a number, or true or false or null, or an object or an array.

really, the app is just doing a `JSON.parse()` on the inputted text, so there's not much I can do for you outside of implementing my own JSON parser (way too much effort for very small reward). I think the real issue lies with the provider of your data

**Comment by NebularNerd** [comment]
No problem thanks for looking. I actually have a couple of API providers returning single quoted data, it's weird but not much we can do about that. I ended up writing my own parser for my python workflows to double quote them, they were causing some interesting hiccups when trying to use them as dictionaries without re-quoting them.
