### ISSUE TITLE
East Slavic

### ISSUE THREAD

**Issue by defadmindef** [joebeachjoebeach/json-path-finder#7]
It appears to me that the path isn't displaying correctly.  Comparing the paths of 
x.Indo-European.Indo-Iranian.Iranian[0]
and 
x.Indo-European.Slavic["East Slavic"][0]
either "Iranian" needs to be in square brackets or "East Slavic" needs a dot notation and not square brackets.  Both hold an array of data, but themselves are part of an object.  Why do they display in the path differently?

x.Indo-European.Indo-Iranian.Iranian[0]
{
  "Indo-European": {
    "Indo-Iranian": {
      "Iranian": [
        "Persian",

x.Indo-European.Slavic["East Slavic"][0]
{
    "Slavic": {
      "East Slavic": [
        "Russian",

**Comment by joebeachjoebeach** [comment]
Hey @defadmindef, thanks for pointing this out!

The reason `East Slavic` is in square brackets is because it contains a space character ` `. This character can't be used in dot notation — `myObj.East Slavic` would evaluate as accessing the `East` property on the `myObj` object, then trying to access the value of a variable called `Slavic`. So it _has_ to be in bracket notation.

There's logic in the app that decides whether a property should be displayed in dot notation or bracket notation. If there's a space in the property value, bracket notation is used.

That being said, your comment made me realize that `Indo-Iranian` also _needs_ to be in bracket notation! The hyphen in that word is evaluated as the minus operator. So, `myObj.Indo-Iranian` is actually trying to subtract the value of a variable `Iranian` from the value of `myObj.Indo`. It ought to be `myObj["Indo-Iranian"]`

I'll need to take some time to re-evaluate the logic I'm using here and update it when I have a chance.

**Comment by joebeachjoebeach** [comment]
Fixed in 1995c894e3a0d14836bcc3a517d7c8e9102b1e03
